# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gain_or_loss', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('fourteen_day_avg_gain', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('fourteen_day_avg_loss', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rsi', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('open', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('market_cap', models.CharField(blank=True, max_length=100, null=True)),
                ('average_volume', models.IntegerField(blank=True, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('short_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('pe', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('peg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='daydata',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DailyData', to='Data.Stock', unique_for_date=b'date'),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Advanced_Stats', to='Data.DayData'),
        ),
    ]
