# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('date', models.DateField()),
                ('open', models.IntegerField(blank=True)),
                ('close', models.IntegerField(blank=True)),
                ('high', models.IntegerField(blank=True)),
                ('low', models.IntegerField(blank=True)),
                ('volume', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='daydata',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DailyData', to='Data.Stock', unique_for_date=b'date'),
        ),
    ]
