# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_auto_20160701_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedstats',
            name='rsi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
