# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_auto_20160701_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedstats',
            name='stoch_rsi',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='advancedstats',
            name='rsi',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
    ]
