# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0006_auto_20160702_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedstats',
            name='macd_signal_line',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='twelve_day_ema',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='twenty_six_day_ema',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True),
        ),
    ]
