# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0007_auto_20160629_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='market_cap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
