# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0007_auto_20160702_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedstats',
            name='fourteen_day_avg_gain',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='advancedstats',
            name='fourteen_day_avg_loss',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='advancedstats',
            name='gain_or_loss',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='advancedstats',
            name='rsi',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='advancedstats',
            name='stoch_rsi',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True),
        ),
    ]
