# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0009_auto_20160705_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedstats',
            name='on_balance_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
