# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0010_advancedstats_on_balance_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedstats',
            name='money_flow_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='money_flow_ratio',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
