# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0011_auto_20160705_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedstats',
            name='money_flow_ratio',
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='fourteen_day_neg_flow',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='advancedstats',
            name='fourteen_day_pos_flow',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
