# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimitAlgorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rsi_low', models.IntegerField()),
                ('rsi_high', models.IntegerField()),
                ('stoch_low', models.IntegerField()),
                ('stoch_high', models.IntegerField()),
                ('mfi_low', models.IntegerField()),
                ('mfi_high', models.IntegerField()),
                ('percent_tolerance', models.DecimalField(decimal_places=5, max_digits=5)),
            ],
            options={
                'db_table': 'limitalgorithm',
            },
        ),
    ]
